- name: join clients to domain
  hosts: clients
  vars:
  gather_facts: yes
  tasks:
    - name: join host to melody.mayhem with automatic reboot
      ansible.builtin.debug:
        msg: "{{ inventory_hostname }}"
    - name: Change the hostname
      win_hostname:
        name: '{{ inventory_hostname }}'
      register: res
    - name: Reboot
      win_reboot:
      when: res.reboot_required
    - name: join to melody.mayhem  
      win_domain_membership:
        dns_domain_name: "melody.mayhem"
        hostname: "{{ inventory_hostname }}"
        domain_admin_user: "Administrator@melody.mayhem"
        domain_admin_password: "P@ssw0rd"
        state: domain
      register: domain_state
    - name: Reboot
      win_reboot:
      when: domain_state.reboot_required
