- name: Give rustdesk access for blue windows
  hosts: bwindows
  gather_facts: yes
  tasks:
    - name: Transfer the script
      ansible.windows.win_copy:
        src: blue_rustdesk.ps1
        dest: C:\blue_rustdesk.ps1
    - name: transfer IE disable script
      ansible.windows.win_copy:
        src: disable_IE.ps1
        dest: C:\disable_IE.ps1
    - name: disable IE and UAC
      ansible.windows.win_powershell:
        script: C:\disable_IE.ps1
    - name: run rustdesk creation 
      ansible.windows.win_powershell:
        script: C:\blue_rustdesk.ps1    
      register: redRust

    - name: rustdesk output
      debug: 
        msg: "{{ redRust.output }}"
