- name: Create FTP Service
  hosts: Stage
  gather_facts: yes
  become: yes
  tasks:
    - name: installing vsftpd package
      apt:
        name: vsftpd
        state: present
        update_cache: true
    - name: configuring systemd for vsftpd
      systemd:
        name: vsftpd
        daemon_reload: true
        enabled: true
