---
# Main Playbook draft
- name: Authenticate Ansible Host
  gather_facts: no
  hosts: localhost
  tags: router,instance
  tasks:

    - block:
        - name: Run Test OpenStack Command
          shell: "openstack server list"

        - debug:
            msg: "Ansible Host is authenticated!"

      rescue:

        - fail:
            msg: "Ansible Host is not authenticated! 
              Please run the openstack rc script and try again"

# Create Networks
# We might need to update /etc/resolv.conf after this script runs b/c it changes it
- name: Create Networks
  tags: router
  import_playbook: pfSense_network.yml

# Will need to get network id somehow if previous is done
- name: Create OpenStack Instances
  tags: instance
  import_playbook: create_instances.yml

- name: Pause For Hosts to Startup
  hosts: localhost
  tags: instance
  tasks:
    - name: pause for 7 min
      pause:
        minutes: 7
# Copy playbook / roles into infra dir
# Each playbook file can decide how to interact w/ hosts and how to set thingup
# Just need to make sure each playbook uses vars in the host file
- name: Active Directory Service 1
  tags: service,ad
  import_playbook: new_domain_controller.yml

- name: add dns entries
  tags: service,addDNS 
  import_playbook: add_dns_entries.yml

- name: Active Directory Secondary DC
  tags: service,ad
  import_playbook: create_ad2.yml

- name: updateDNS for all Hosts
  tags: service,dns
  import_playbook: updateDNS.yml

- name: Add windows clients to melody.mayhem
  tags: service,clients
  import_playbook: add_clients_to_domain.yml

- name: add AD Users
  tags: service,user,wuser 
  import_playbook: create_users.yml 

- name: add Local Windows Users
  tags: service,user,wuser
  import_playbook: create_local_users.yml

- name: add Local Linux Users
  tags: service,user,luser
  import_playbook: add_users.yml

- name: Smb Creation
  tags: service,smb
  import_playbook: deploy_smb.yml

- name: Install SQL
  tags: service,sql
  import_playbook: installsql.yml

- name: Install FTP
  tags: service,ftp
  import_playbook: install_ftp.yml

- name: Install HTTP
  tags: service,http
  import_playbook: webserver_setup.yml

- name: Install Telnet
  tags: service,telnet
  import_playbook: install_telnet.yml

- name: update all hosts
  tags: service,update
  import_playbook: updateHosts.yml

- name: install ssh on windows
  tags: service,ssh 
  import_playbook: installWinSSH.yml

- name: red linux rustdesk access
  tags: service,rustdesk
  import_playbook: red_rustdesk.yml

- name: red windows rustdesk access
  tags: service,rustdesk
  import_playbook: red_rustdeskWin.yml

- name: blue linux rustdesk access
  tags: service,rustdesk
  import_playbook: blue_rustdesk.yml

- name: blue windows rustdesk access
  tags: service, rustdesk,wrustdesk
  import_playbook: blue_rustdeskWin.yml
# EXAMPLE
#- name: Setup Service 0
#  tags: service
#  import_playbook: [service playbook file]
# ....
#- name: Setup Service N
#  tags: service
#  import_playbook: [service playbook file]

# tags allow for certain tasks to be run ie
# Setup ENTIRE infra:             ansible-playbook -i <inventory> --tags router,instance,service main.yml
# Setup JUST boxes and services: ansible-playbook -i <inventory> --tags instance,service main.yml
# Setup JUST services:           ansible-playbook -i <inventory> --tags service main.yml
