- name: Give rustdesk access for red
  hosts: rlinux
  gather_facts: yes
  become: yes
  tasks:
    - name: Transfer the script
      copy: src=red_rustdesk.sh dest=/tmp/red_rustdesk.sh mode=0777
    - name: red rustdesk acecss
      command: sh /tmp/red_rustdesk.sh
      register: redRust

    - name: rustdesk output
      debug: 
        msg: "{{ redRust.stdout }}"
