---
- name: test
  hosts: localhost
  gather_facts: no
  vars:
    local_users_file: lusers.txt
  tasks:


    - debug:
        msg: "{{ item }}"
      with_items: "{{ lookup('file', local_users_file).split('\n') }}"
