---
- name: "Setting dns nameservers and resolv domains"
  hosts: "all"
  roles:
    - role: "change_dns"
      resolv_nameservers:
        - "192.168.3.15"
        - "192.168.3.16"
        - "8.8.8.8"
      resolv_domain: "melody.mayhem"
