---
# tasks file for addLocalUsers
# Zach Riback
# 2/7/2024
# Alpha - 2235
# Role to create the local users for Windows boxes


- name: Create unpriv local windows users
  ansible.windows.win_user:
    name: "{{ item }}"
    password: "{{ default_user_password }}"
    state: present
    groups:
      - Users
  with_items: "{{ lookup('file', unpriv_users).split('\n') }}"
  ignore_errors: true


- name: Create priv local windows users
  ansible.windows.win_user:
    name: "{{ item }}"
    password: "{{ default_admin_password }}"
    state: present
    groups:
      - Users
      - Administrators
  with_items: "{{ lookup('file', priv_users).split('\n') }}"
